### ISSUE TITLE
Spring Framework - Context Initialization failed

### ISSUE THREAD

**Issue by jhulick** [leleuj/cas-overlay-demo#10]
After following the build instructions I receive a runtime error on Spring startup. It looks like there are dependencies missing? The application cannot find this class: org.jasig.cas.authentication.handler.support.SimpleTestUsernamePasswordAuthenticationHandler

Do you have suggestions on a fix? 

Stack trace below:

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'memcachedTicketRegistry': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.jasig.cas.util.CipherExecutor org.jasig.cas.ticket.registry.encrypt.AbstractCrypticTicketRegistry.cipherExecutor; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.jasig.cas.authentication.handler.support.SimpleTestUsernamePasswordAuthenticationHandler] for bean with name 'primaryAuthenticationHandler' defined in ServletContext resource [/WEB-INF/deployerConfigContext.xml]; nested exception is java.lang.ClassNotFoundException: org.jasig.cas.authentication.handler.support.SimpleTestUsernamePasswordAuthenticationHandler

**Comment by leleuj** [comment]
If you want something stable, you should use the 4.1.x branch.

This demo is based on the latest CAS SNAPSHOT and is regularly broken. I will fix that shortly.

**Comment by leleuj** [comment]
It's fixed now.
