### ISSUE TITLE
Could not resolve dependencies for project org.leleuj :cas-overlay-server-demo:war:4.2.0-SNAPSHOT: Failure to find org.jasig.cas:cas-server-integration-restlet:jar:4.2.0-RC2

### ISSUE THREAD

**Issue by jorgefdez205** [leleuj/cas-overlay-demo#15]
I tried branch 4.2.x and got different error: [ERROR] Failed to execute goal on project cas-overlay-server-demo: Could not resolve dependencies for project org.leleuj
:cas-overlay-server-demo:war:4.2.0-SNAPSHOT: Failure to find org.jasig.cas:cas-server-integration-restlet:jar:4.2.0-RC2

**Comment by leleuj** [comment]
The name of the module has changed: it's fixed in branch 4.2.x
