### ISSUE TITLE
Application Not Authorized to Use CAS

### ISSUE THREAD

**Issue by charybr** [leleuj/cas-overlay-demo#18]
Thanks very much, for giving this example!

I was getting error - Application Not Authorized to Use CAS.
I had to edit file localhost-2.json located at cas-overlay-demo-master/cas-overlay-server-demo/src/main/resources/services/.
Changed 
"serviceId" : "^https?://localhost.*",
to
"serviceId" : "^http?://localhost.*",

After this, it worked.

**Comment by leleuj** [comment]
It's of course just an example you can start from.
