### ISSUE TITLE
Problem accessing /cas/login. Reason:      Service Unavailable

### ISSUE THREAD

**Issue by sckoh** [leleuj/cas-overlay-demo#9]
when i access http://localhost:8080/cas-management 

It is redirected to http://localhost:8080/cas/login?service=http%3A%2F%2Flocalhost%3A8080%2Fcas-management%2Flogin%2Fcas

HTTP ERROR: 503

Problem accessing /cas/login. Reason:

    Service Unavailable

**Comment by leleuj** [comment]
Strange! I remember starting it a few days / weeks ago. You should have some error in your logs (maybe at startup): what's your stacktrace?

**Comment by sckoh** [comment]
There are no error. It started successfully

**Comment by leleuj** [comment]
I have a Memcached error at startup. So either you can remove the Memcached dependency or you can wait for this issue to be resolved: https://github.com/Jasig/cas/issues/1252
